# Generated by Django 3.0.4 on 2020-04-11 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SpecName', models.CharField(max_length=50)),
                ('SpecValue', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompName', models.CharField(max_length=100)),
                ('Company', models.CharField(default='None', max_length=100)),
                ('Description', models.TextField(blank=True, null=True)),
                ('State', models.CharField(default='INA', max_length=50)),
                ('NextState', models.CharField(default='Make', max_length=50)),
                ('AvgPrice', models.DecimalField(decimal_places=2, max_digits=20)),
                ('Spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='components.Specification')),
            ],
        ),
    ]
