# Generated by Django 3.0.4 on 2020-04-11 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specification',
            name='SpecName',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='specification',
            name='SpecValue',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
