# Generated by Django 3.0.4 on 2020-04-06 11:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='component',
            old_name='title',
            new_name='CompName',
        ),
        migrations.RenameField(
            model_name='component',
            old_name='description',
            new_name='Description',
        ),
        migrations.AddField(
            model_name='component',
            name='NextState',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='component',
            name='State',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
